version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres_db_nextjs_dashboard
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network_nextjs_dashboard

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_4_db_nextjs_dashboard
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres # Ensures pgAdmin starts after PostgreSQL
    networks:
      - pg_network_nextjs_dashboard

networks:
  pg_network_nextjs_dashboard:
    driver: bridge

volumes:
  postgres_data:
